---
title: "cellcycle"
format: html
editor: visual
---

```{r}
# Loading relevant libraries 
library(tidyverse) # includes ggplot2, for data visualisation. dplyr, for data manipulation.
library(Seurat)
library(scuttle)
set.seed(123)
```

```{r}
poolA_et_B <-  readRDS("020_010_042_025_008_034_095_017_filtered_with_adt_qc_outlierdrop_norm_dimred_annot_sex.rds")
```

## Cell cycle cyclone

```{r}
library(org.Hs.eg.db)
library(scran)
library(dplyr)
library(ggplot2)


# 2. Créer un vecteur de conversion
# On récupère les symbols correspondant aux IDs Ensembl
indices <- match(rownames(poolA_et_B), mapping$ensembl_gene_id)
new_names <- mapping$hgnc_symbol[indices]

# 3. LA LOGIQUE DE SAUVETAGE :
# On ne remplace que si le nouveau nom n'est pas NA et n'est pas vide ("")
# Sinon, on garde le nom d'origine (qui est déjà un Symbol ou un ID inconnu)
final_names <- ifelse(is.na(new_names) | new_names == "", 
                      rownames(poolA_et_B), 
                      new_names)

# 4. Gérer les doublons (très fréquent après conversion)
# Si deux IDs Ensembl pointent vers le même Symbol, Seurat va planter
final_names <- make.unique(final_names)

# 5. Appliquer à l'objet Seurat
rownames(poolA_et_B) <- final_names

# 1. Get training data (Human)
hs.pairs <- readRDS(system.file("exdata", "human_cycle_markers.rds", package="scran"))

# 2. Run cyclone (needs a SingleCellExperiment object or raw matrix)
# Note: This can be slow on large datasets
assignments <- cyclone(poolA_et_B, pairs=hs.pairs, gene.names=rownames(poolA_et_B))

# 3. Add back to Seurat Metadata
poolA_et_B$phases <- assignments$phases
poolA_et_B$G1.score <- assignments$scores$G1
poolA_et_B$G2M.score <- assignments$scores$G2M

# Visualize to see if specific clusters are "stuck" in G1 (potential resistant cells)
DimPlot(poolA_et_B, group.by = "phases")

# ==============================================================================
# 1. CONVERSION DES IDS ENSEMBL -> SYMBOLS (SANS "LOC")
# ==============================================================================
hm.pairs <- readRDS(system.file("exdata", "human_cycle_markers.rds", package="scran"))
counts_mat <- GetAssayData(poolA_et_B, layer = "counts")

# 3. Run cyclone using the UPPERCASE list names
# and explicitly passing the rownames as the gene.names
assignments <- cyclone(
  x = counts_mat, 
  pairs = hm.pairs, 
  gene.names = rownames(counts_mat)
)

# Extraction des IDs originaux
ensembl_ids <- rownames(poolA_et_B)

# 4. Check the results
head(assignments$scores)

# Visualisation de la quiescence (G1) vs Prolifération (S/G2M)
VlnPlot(poolA_et_B, features = c("S.Score", "G2M.Score"), group.by = "response")
```

```{r}
# Define cell cycle stage per cell
set.seed(100)
hm.pairs <- readRDS(system.file("exdata", "human_cycle_markers.rds", package="scran"))
assignments <- cyclone(poolA_et_B, hm.pairs, gene.names=rownames(poolA_et_B))

phases_info <- data.frame(phases = assignments$phases, G1_score = assignments$scores$G1,
                          G2M_score = assignments$scores$G2M, S_score = assignments$scores$S)
phases_info$phases[which(phases_info$phases=="G1")] <- "G1_G0"
phases_info$phases[which(phases_info$phases=="G2M")] <- "G2_M"
rownames(phases_info)<-colnames(input)
tab <- table(assignments$phases)

par(mfrow=c(1,1))
plot(phases_info$G1_score, phases_info$G2M_score, col=color_phases[phases_info$phases],
     xlab="G1 score", ylab="G2/M score", main = paste0(paste(names(tab), tab, sep = ": "),collapse=" - "), pch=16)
abline(h=.5,col="gray",lty=2,lwd=1.2)
abline(v=.5,col="gray",lty=2,lwd=1.2)
legend("topright", names(color_phases),fill=color_phases,bty="n")

phases_info$keep_from_CC <- FALSE
phases_info$keep_from_CC[which(is.na(phases_info$G2M_score) == FALSE & is.na(phases_info$S_score) == FALSE &
                                 is.na(phases_info$G1_score) == FALSE & is.na(phases_info$phases) == FALSE )] <- TRUE
poolA_et_B <- AddMetaData(poolA_et_B, metadata=phases_info)

print(paste("Matrix dim before cell filtering : ", paste0(dim(seurat), collapse = "-"),sep=""))

print("Are all cell cycle predictions valid?")
table(poolA_et_B@meta.data$keep_from_CC)
poolA_et_B <- subset(poolA_et_B, subset = keep_from_CC != FALSE)

VlnPlot(poolA_et_B, features = c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.ribo"),  split.by = 'sex',ncol = 2, pt.size =0)

```

```{r}
library(dplyr)
library(ggplot2)

color_phases <- c("#FCC5C0", "#DD3497", "#49006A")
names(color_phases) <- c("G1", "S","G2M")

# On force l'utilisation de dplyr::count pour éviter les conflits
df_plot <- poolA_et_B@meta.data %>%
  dplyr::count(Phase, response) %>% # Attention : Phase avec un P majuscule
  group_by(response) %>%
  mutate(percentage = n / sum(n) * 100)

# Création du graphique en barres empilées (Proportions)
ggplot(df_plot, aes(x = response, y = percentage, fill = Phase)) +
  geom_bar(stat = "identity", position = "dodge")  +
  scale_fill_manual(values = color_phases) + # Applique vos couleurs
  labs(title = "Répartition des Phases du Cycle Cellulaire",
       y = "Pourcentage de cellules (%)",
       x = "Groupe de réponse")
```

```{r}
poolA_et_B@meta.data %>%
  dplyr::count(patient ,Phase) %>%
  ggplot(aes(x = patient, y = n, fill = Phase)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_bw() +
  labs(
    x = "samples",
    y = "nbr de cell",
    fill = "cell_cycle"
  )
```

## cell-cycle seurat

```{r}
# Read in the expression matrix The first row is a header row, the first column is rownames
exp.mat <- read.table(file = "C:/Users/Chellal/Downloads/cell_cycle_vignette_files/nestorawa_forcellcycle_expressionMatrix.txt",
    header = TRUE, as.is = TRUE, row.names = 1)

# A list of cell cycle markers, from Tirosh et al, 2015, is loaded with Seurat.  We can
# segregate this list into markers of G2/M phase and markers of S phase
s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes

poolA_et_B <- CellCycleScoring(poolA_et_B, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)

# Assurez-vous que les noms de la palette correspondent exactement aux niveaux de Phase
# (G1, S, G2M)
Idents(poolA_et_B) <- poolA_et_B$Phase

DimPlot(poolA_et_B, reduction = "umap.integrated") + 
  scale_color_manual(values = color_phases) +
  theme_bw() + # Optionnel, pour un fond propre
  ggtitle("Cell Cycle Phase Distribution on UMAP")

poolA_et_B@meta.data %>%
  dplyr::count(Phase) %>%
  ggplot(aes(x = Phase, y = n, fill = Phase)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_bw() +
  labs(
    x = "samples",
    y = "nbr de cell",
    fill = "cell_cycle"
  )

poolA_et_B@meta.data %>%
  dplyr::count(patient ,Phase) %>%
  ggplot(aes(x = patient, y = n, fill = Phase)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_bw() +
  labs(
    x = "samples",
    y = "nbr de cell",
    fill = "cell_cycle"
  )

oo@meta.data %>%
  dplyr::count( renamed_cell_type, Phase) %>%
  ggplot(aes(x = renamed_cell_type, y = n, fill = Phase)) +
  geom_bar(stat = "identity", position = "dodge")  +
  scale_fill_manual(values = color_phases) +
  theme_bw() +
  labs(
    x = "samples",
    y = "nbr de cell",
    fill = "cell_cycle"
  )

```

## doublet

```{r}
library(DoubletFinder)

Idents(poolA_et_B) <- "orig.ident"

## pK Identification (no ground-truth) ---------------------------------------------------------------------------------------
sweep.res.list_aml <- paramSweep(poolA_et_B, PCs = 1:20, sct = FALSE)
sweep.stats_aml <- summarizeSweep(sweep.res.list_aml, GT = FALSE)
bcmvn_aml <- find.pK(sweep.stats_aml)

## pK Identification (ground-truth) ------------------------------------------------------------------------------------------
sweep.res.list_aml <- paramSweep(poolA_et_B, PCs = 1:20, sct = FALSE)
gt.calls <- poolA_et_B@meta.data[rownames(sweep.res.list_aml[[1]]), "GT"]   ## GT is a vector containing "Singlet" and "Doublet" calls recorded using sample multiplexing classification and/or in silico geneotyping results 
bcmvn_aml <- find.pK(sweep.stats_aml)

## Homotypic Doublet Proportion Estimate -------------------------------------------------------------------------------------
nExp_poi <- round(0.075*nrow(poolA_et_B@meta.data))  ## Assuming 7.5% doublet formation rate - tailor for your dataset
nExp_poi.adj <- round(nExp_poi*(1-homotypic.prop))

poolA_et_B <- doubletFinder(poolA_et_B, PCs = 1:20, pN = 0.25, pK = 0.01, nExp = nExp_poi, reuse.pANN = NULL, sct = FALSE)

Idents(poolA_et_B) <- "DF.classifications_0.25_0.01_1814"

DimPlot(poolA_et_B, reduction = "umap.integrated")
```

#save

```{r}
saveRDS(poolA_et_B, file = "020_010_042_025_008_034_095_017_filtered_with_adt_qc_outlierdrop_norm_dimred_annot_sex_phase.rds")
```
