---
title: "analysis"
format: html
editor: visual
---


```{r}
# Loading relevant libraries 
library(tidyverse) # includes ggplot2, for data visualisation. dplyr, for data manipulation.
library(Seurat)
library(scuttle)
```

```{r}
poolA_et_B <-  readRDS("020_010_042_025_008_034_095_017_filtered_with_adt_qc_outlierdrop_norm_dimred_annot_sex_phase.rds")
```

### par cluster

```{r}
Idents(poolA_et_B) <- "seurat_clusters"

markers_cluster <- FindMarkers(
  subset(poolA_et_B, idents = 3),
  group.by = "response",
  ident.1 = "refractory",
  ident.2 = "responder"
)

# Création du tableau final trié par puissance d'expression (Log2FC)
liste_resistance <- markers_P1[genes_communs, ] %>% arrange(desc(avg_log2FC))

# ==============================================================================
# 4. VISUALISATION FINALE
# ==============================================================================

# Afficher les 10 gènes les plus discriminants
top30_genes <- head(rownames(liste_resistance), 30)
```
